services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: tradeforge-frontend
    ports:
      - "8080:8080"
    environment:
      MARKET_URL: http://market-service:8000
      WALLET_URL: http://wallet-service:8000
      ORDER_URL: http://order-service:8000
      PORTFOLIO_URL: http://portfolio-service:8000
      RECO_URL: http://recommendation-service:8000
    depends_on:
      - market-service
      - wallet-service
      - order-service
      - portfolio-service
      - recommendation-service

  market-service:
    build:
      context: .
      dockerfile: services/market_service/Dockerfile
    container_name: tradeforge-market
    ports:
      - "8001:8000"

  wallet-service:
    build:
      context: .
      dockerfile: services/wallet_service/Dockerfile
    container_name: tradeforge-wallet
    ports:
      - "8004:8000"

  order-service:
    build:
      context: .
      dockerfile: services/order_service/Dockerfile
    container_name: tradeforge-order
    ports:
      - "8005:8000"
    environment:
      WALLET_URL: http://wallet-service:8000
      PORTFOLIO_URL: http://portfolio-service:8000
    depends_on:
      - wallet-service
      - portfolio-service

  portfolio-service:
    build:
      context: .
      dockerfile: services/portfolio_service/Dockerfile
    container_name: tradeforge-portfolio
    ports:
      - "8002:8000"

  recommendation-service:
    build:
      context: .
      dockerfile: services/recommendation_service/Dockerfile
    container_name: tradeforge-recommendation
    ports:
      - "8003:8000"
